-- Scripter Backend Database Schema
-- Generated by Drizzle Kit
-- Version: 1.0.0

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  avatar TEXT,
  plan TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'creator', 'pro', 'studio')),
  ai_quota JSONB NOT NULL DEFAULT '{"monthlyLimit":500000,"used":0,"resetAt":"2025-01-26T00:00:00.000Z"}',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Projects table
CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  genre JSONB NOT NULL DEFAULT '[]',
  script_type TEXT NOT NULL CHECK (script_type IN ('movie', 'series', 'short-drama')),
  orientation TEXT NOT NULL CHECK (orientation IN ('landscape', 'portrait')),
  target_episodes INTEGER NOT NULL,
  current_stage TEXT NOT NULL CHECK (current_stage IN ('worldview', 'character', 'script', 'optimize', 'production')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Characters table
CREATE TABLE IF NOT EXISTS characters (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  poem TEXT,
  basic_info JSONB NOT NULL,
  personality JSONB NOT NULL DEFAULT '[]',
  speech_style TEXT NOT NULL,
  behavior_pattern TEXT NOT NULL,
  growth_arc TEXT NOT NULL,
  relationships JSONB NOT NULL DEFAULT '[]',
  avatar TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Scenes table
CREATE TABLE IF NOT EXISTS scenes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  episode_number INTEGER NOT NULL DEFAULT 1,
  scene_number INTEGER NOT NULL,
  location TEXT NOT NULL,
  time_of_day TEXT NOT NULL,
  int_ext TEXT NOT NULL,
  content JSONB NOT NULL,
  duration INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'completed')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Worldview items table
CREATE TABLE IF NOT EXISTS worldview_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('era', 'geography', 'social', 'mystery', 'culture', 'economy', 'custom')),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Storyboards table
CREATE TABLE IF NOT EXISTS storyboards (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  scene_id UUID NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
  shot_number INTEGER NOT NULL,
  shot_type TEXT NOT NULL,
  angle TEXT NOT NULL,
  movement TEXT NOT NULL,
  description TEXT NOT NULL,
  audio TEXT NOT NULL,
  duration INTEGER NOT NULL DEFAULT 0,
  reference_image TEXT,
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- AI conversations table
CREATE TABLE IF NOT EXISTS ai_conversations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  agent TEXT NOT NULL,
  messages JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Juling configs table
CREATE TABLE IF NOT EXISTS juling_configs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '剧灵',
  birth_date TIMESTAMP NOT NULL DEFAULT NOW(),
  personality JSONB NOT NULL DEFAULT '{"elements":[],"style":"温暖、鼓励、专业的创作伙伴"}',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Creative milestones table
CREATE TABLE IF NOT EXISTS creative_milestones (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('first_scene', 'first_episode', 'completed')),
  achieved_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ai_contribution INTEGER NOT NULL DEFAULT 0
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at ON projects(updated_at);

CREATE INDEX IF NOT EXISTS idx_characters_project_id ON characters(project_id);

CREATE INDEX IF NOT EXISTS idx_scenes_project_id ON scenes(project_id);
CREATE INDEX IF NOT EXISTS idx_scenes_episode_number ON scenes(episode_number);

CREATE INDEX IF NOT EXISTS idx_worldview_items_project_id ON worldview_items(project_id);
CREATE INDEX IF NOT EXISTS idx_worldview_items_category ON worldview_items(category);

CREATE INDEX IF NOT EXISTS idx_storyboards_project_id ON storyboards(project_id);
CREATE INDEX IF NOT EXISTS idx_storyboards_scene_id ON storyboards(scene_id);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_id ON ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_project_id ON ai_conversations(project_id);

CREATE INDEX IF NOT EXISTS idx_juling_configs_user_id ON juling_configs(user_id);

CREATE INDEX IF NOT EXISTS idx_creative_milestones_user_id ON creative_milestones(user_id);
CREATE INDEX IF NOT EXISTS idx_creative_milestones_project_id ON creative_milestones(project_id);
